// import { format } from "date-fns";

const LOGIN = "/login";
const CARE_PACKAGE = "/care-package";
const HOME_CARE = `${CARE_PACKAGE}/home-care`;
const HOME_CARE_APPROVE_PACKAGE = `${HOME_CARE}/approve-package`;
const HOME_CARE_APPROVE_BROKERED = `${HOME_CARE}/approve-brokered`;
const NURSING_CARE = `${CARE_PACKAGE}/nursing-care`;
const NURSING_CARE_APPROVE_PACKAGE = `${NURSING_CARE}/approve-package`;
const NURSING_CARE_APPROVE_BROKERED = `${NURSING_CARE}/approve-brokered`;
const RESIDENTIAL_CARE = `${CARE_PACKAGE}/residential-care`;
const RESIDENTIAL_CARE_APPROVE_PACKAGE = `${RESIDENTIAL_CARE}/approve-package`;
const RESIDENTIAL_CARE_APPROVE_BROKERED = `${RESIDENTIAL_CARE}/approve-brokered`;
const DAY_CARE = `${CARE_PACKAGE}/day-care`;
const DAY_CARE_APPROVE_PACKAGE = `${DAY_CARE}/approve-package`;
const DAY_CARE_APPROVE_BROKERED = `${DAY_CARE}/approve-brokered`;
const CLIENT_HISTORY = "/client-history";

export {
  LOGIN,
  HOME_CARE,
  HOME_CARE_APPROVE_PACKAGE,
  HOME_CARE_APPROVE_BROKERED,
  DAY_CARE,
  DAY_CARE_APPROVE_PACKAGE,
  DAY_CARE_APPROVE_BROKERED,
  NURSING_CARE,
  NURSING_CARE_APPROVE_PACKAGE,
  NURSING_CARE_APPROVE_BROKERED,
  RESIDENTIAL_CARE,
  RESIDENTIAL_CARE_APPROVE_PACKAGE,
  RESIDENTIAL_CARE_APPROVE_BROKERED,
  CLIENT_HISTORY,
  CARE_PACKAGE,
};
