const LOGOUT_ROUTE = '/logout';
const BROKERAGE_HUB_ROUTE = '/brokerage-hub';
const CARE_PACKAGE_ROUTE = '/care-package';
const BROKERAGE_ROUTE = `${CARE_PACKAGE_ROUTE}/brokerage`;
const BROKER_PACKAGE_ROUTE = `${BROKERAGE_ROUTE}/broker-package`;
const PAYMENTS_ROUTE = '/payments';
const PAYMENTS_PAY_RUNS_ROUTE = `${PAYMENTS_ROUTE}/pay-runs`;
const PAYMENTS_BILLS_ROUTE = `${PAYMENTS_ROUTE}/bills`;

export {
  LOGOUT_ROUTE,
  CARE_PACKAGE_ROUTE,
  PAYMENTS_ROUTE,
  PAYMENTS_BILLS_ROUTE,
  PAYMENTS_PAY_RUNS_ROUTE,
  BROKERAGE_HUB_ROUTE,
  BROKER_PACKAGE_ROUTE,
};
